server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1
    data-username: username
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: create